---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cert-manager-crds.yaml
  - cert-manager-manifests.yaml
  - secret-cf-token.yaml
  - letsencrypt-staging.yaml
