---
# Base cert-manager configuration
# Based on TechnoTim guide: https://technotim.com/posts/kube-traefik-cert-manager-le/

# CRDs must be installed separately:
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.crds.yaml

installCRDs: false
replicaCount: 1

extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
  - --dns01-recursive-nameservers-only

podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 9.9.9.9

startupapicheck:
  enabled: false
