---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-dev

resources:
  - ../base

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 32.1.1
    releaseName: traefik
    namespace: traefik-dev
    valuesFile: values-base.yaml
    additionalValuesFiles:
      - values-dev.yaml
